id: K70n0s510-vscode-settings
info:
  name: Exposed .vscode Settings
  author: K70n0s510
  severity: low
  description: Detects exposed VSCode settings.json which may contain paths or env vars.
  tags: config,ide,vscode
http:
  - method: GET
    path:
      - "{{BaseURL}}/.vscode/settings.json"
      - "{{BaseURL}}/.vscode/sftp.json"
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "editor.tabSize"
          - "files.exclude"
      - type: status
        status: [200]
