id: K70n0s510-exposed-git-config
info:
  name: Exposed .git/config File
  severity: critical
http:
  - method: GET
    path:
      - "{{BaseURL}}/.git/config"
    matchers-condition: and
    matchers:
      - type: status
        status: [200]
      - type: word
        words: ["[core]", "repositoryformatversion"]
