id: K70n0s510-swagger-ui
info:
  name: Public Swagger/OpenAPI Documentation
  severity: low
http:
  - method: GET
    path:
      - "{{BaseURL}}/swagger-ui.html"
      - "{{BaseURL}}/api/docs"
    matchers-condition: and
    matchers:
      - type: status
        status: [200]
      - type: word
        words: ["Swagger UI", "\"openapi\":"]
