id: K70n0s510-swagger-ui
info:
  name: Swagger/OpenAPI Documentation
  author: K70n0s510
  severity: info
  description: Locates API documentation which assists in crafting precise attacks.
http:
  - method: GET
    path:
      - "{{BaseURL}}/swagger-ui.html"
      - "{{BaseURL}}/v2/api-docs"
      - "{{BaseURL}}/openapi.json"
      - "{{BaseURL}}/docs"
    matchers-condition: or
    matchers:
      - type: word
        words:
          - "swagger"
          - "openapi"
          - "\"paths\":"
